export const jobTitles = [
  // Tech & Engineering
  "Software Engineer",
  "Senior Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Product Manager",
  "UX Designer",
  "UI Designer",
  "QA Engineer",
  "System Administrator",
  "Cloud Architect",
  "Cybersecurity Analyst",
  "Network Engineer",
  "Database Administrator",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "Technical Lead",
  "Engineering Manager",
  "CTO",
  "VP of Engineering",
  "Site Reliability Engineer",
  "Blockchain Developer",
  "AR/VR Developer",
  "Game Developer",
  "Technical Writer",
  "Solutions Architect",
  
  // Design & Creative
  "Graphic Designer",
  "Art Director",
  "Creative Director",
  "Copywriter",
  "Content Strategist",
  "Video Editor",
  "Motion Graphics Designer",
  "Illustrator",
  "Fashion Designer",
  "Interior Designer",
  "Industrial Designer",
  "Photographer",
  "Videographer",
  "Animator",
  "Visual Designer",
  "Product Designer",
  "Brand Manager",
  "Social Media Manager",
  "Digital Marketing Specialist",
  "SEO Specialist",
  
  // Sales & Marketing
  "Sales Representative",
  "Account Executive",
  "Sales Manager",
  "Business Development Manager",
  "Marketing Manager",
  "CMO",
  "VP of Sales",
  "Customer Success Manager",
  "Account Manager",
  "Email Marketing Specialist",
  "PPC Specialist",
  "Market Research Analyst",
  "Public Relations Specialist",
  "Event Coordinator",
  "Brand Ambassador",
  "Telemarketer",
  "Inside Sales Representative",
  "Field Sales Representative",
  "Sales Engineer",
  "Growth Hacker",
  
  // Finance & Accounting
  "Accountant",
  "Financial Analyst",
  "CFO",
  "Controller",
  "Auditor",
  "Bookkeeper",
  "Investment Banker",
  "Tax Specialist",
  "Payroll Specialist",
  "Risk Analyst",
  "Compliance Officer",
  "Underwriter",
  "Actuary",
  "Financial Planner",
  "Portfolio Manager",
  "Credit Analyst",
  "Treasury Analyst",
  "Billing Specialist",
  "Accounts Payable Clerk",
  "Accounts Receivable Clerk",
  
  // HR & Administration
  "HR Manager",
  "Recruiter",
  "Talent Acquisition Specialist",
  "HR Generalist",
  "Benefits Administrator",
  "Training Manager",
  "Office Manager",
  "Executive Assistant",
  "Administrative Assistant",
  "Receptionist",
  "Chief People Officer",
  "Operations Manager",
  "Project Manager",
  "Program Manager",
  "Scrum Master",
  "Product Owner",
  "Business Analyst",
  "Virtual Assistant",
  "Data Entry Clerk",
  "Customer Service Representative",
  
  // Healthcare & Medical
  "Registered Nurse",
  "Nurse Practitioner",
  "Physician",
  "Surgeon",
  "Medical Assistant",
  "Pharmacist",
  "Physical Therapist",
  "Occupational Therapist",
  "Dentist",
  "Dental Hygienist",
  "Radiologic Technologist",
  "Laboratory Technician",
  "Phlebotomist",
  "Medical Biller",
  "Medical Coder",
  "Health Services Manager",
  "Clinical Research Coordinator",
  "Nutritionist",
  "Dietitian",
  "Paramedic",
  
  // Education & Training
  "Teacher",
  "Professor",
  "Lecturer",
  "School Principal",
  "Guidance Counselor",
  "Librarian",
  "Instructional Designer",
  "Curriculum Developer",
  "Special Education Teacher",
  "Tutor",
  "Education Administrator",
  "Research Assistant",
  "Academic Advisor",
  "Coach",
  "Trainer",
  
  // Legal
  "Lawyer",
  "Attorney",
  "Paralegal",
  "Legal Assistant",
  "General Counsel",
  "Compliance Manager",
  "Contract Manager",
  "Judge",
  "Court Reporter",
  "Mediator",
  
  // Manufacturing & Logistics
  "Production Manager",
  "Quality Control Inspector",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Warehouse Manager",
  "Inventory Specialist",
  "Machine Operator",
  "Forklift Operator",
  "Truck Driver",
  "Purchasing Manager",
  "Procurement Specialist",
  "Safety Manager",
  "Maintenance Technician",
  "Electrician",
  "Plumber",
  "Welder",
  "Carpenter",
  "Mechanic",
  "Construction Manager",
  "Civil Engineer",
  
  // Hospitality & Service
  "Hotel Manager",
  "Restaurant Manager",
  "Chef",
  "Sous Chef",
  "Cook",
  "Bartender",
  "Server",
  "Host/Hostess",
  "Concierge",
  "Housekeeper",
  "Travel Agent",
  "Event Planner",
  "Flight Attendant",
  "Pilot",
  
  // Science & Research
  "Research Scientist",
  "Biologist",
  "Chemist",
  "Physicist",
  "Geologist",
  "Environmental Scientist",
  "Forensic Scientist",
  "Lab Manager",
  "Statistician",
  "Economist",
  
  // Other
  "Consultant",
  "Freelancer",
  "Intern",
  "Volunteer",
  "Founder",
  "CEO",
  "President",
  "Director",
  "Manager",
  "Associate",
  "Analyst",
  "Coordinator",
  "Specialist",
  "Technician",
  "Assistant",
].sort();

export const jobLevels = [
  "Intern",
  "Junior",
  "Mid-Level",
  "Senior",
  "Lead",
  "Principal",
  "Staff",
  "Director",
  "VP",
  "Head of",
  "Executive",
];
